'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { RefButton as RefButtonElement, defineCustomElement as defineRefButton } from "@reference-ui/core/dist/components/ref-button.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type RefButtonEvents = NonNullable<unknown>;

export const RefButton: StencilReactComponent<RefButtonElement, RefButtonEvents> = /*@__PURE__*/ createComponent<RefButtonElement, RefButtonEvents>({
    tagName: 'ref-button',
    elementClass: RefButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as RefButtonEvents,
    defineCustomElement: defineRefButton
});
