/** Generated by @reference-ui/cli - do not edit by hand */
import { createPandaConfig } from '@reference-ui/system'

export default createPandaConfig({
  cwd: process.cwd(),
  outDir: '.reference',
  include: ["src/**/*.{ts,tsx}","../reference-core/src/**/*.{ts,tsx}"],
})
