import { writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { resolvePackageRoot } from './resolve-consumer.js'
import { loadReferenceConfig } from './load-config.js'
import { runPanda } from './run-panda.js'
import { buildRuntimeToDotReference, buildSystemToDotReference, copyRuntimeToNodeModules } from './copy-runtime.js'

const OUT_DIR = '.reference'
const DEFAULT_INCLUDE = [
  'src/**/*.{ts,tsx}',
  'node_modules/@reference-ui/core/**/*.{ts,tsx}',
]

function writePandaConfig(packageRoot: string, include: string[]): void {
  const configContent = `/** Generated by @reference-ui/cli - do not edit by hand */
import { createPandaConfig } from '@reference-ui/system'

export default createPandaConfig({
  cwd: process.cwd(),
  outDir: '${OUT_DIR}',
  include: ${JSON.stringify(include)},
})
`
  const configPath = resolve(packageRoot, 'panda.config.ts')
  writeFileSync(configPath, configContent, 'utf-8')
}

/**
 * Run sync: write panda.config.ts, run panda codegen + cssgen, build runtime into
 * .reference/runtime/core, then copy to node_modules/@reference/core so consumers
 * can import from @reference/core.
 */
export function runSync(startCwd?: string): { ok: boolean; packageRoot: string } {
  const packageRoot = resolvePackageRoot(startCwd ?? process.cwd())
  const config = loadReferenceConfig(packageRoot)
  const include = config.include?.length ? config.include : DEFAULT_INCLUDE

  writePandaConfig(packageRoot, include)

  if (!runPanda(packageRoot, ['codegen'])) {
    return { ok: false, packageRoot }
  }

  // Output CSS to styled-system/styles.css (standard Panda location)
  const outFile = 'styled-system/styles.css'
  const outPath = resolve(packageRoot, outFile)
  mkdirSync(dirname(outPath), { recursive: true })
  if (!runPanda(packageRoot, ['cssgen', '--outfile', outFile])) {
    return { ok: false, packageRoot }
  }

  try {
    buildRuntimeToDotReference(packageRoot)
    buildSystemToDotReference(packageRoot)
    copyRuntimeToNodeModules(packageRoot)
  } catch (err) {
    console.error(err instanceof Error ? err.message : err)
    return { ok: false, packageRoot }
  }

  return { ok: true, packageRoot }
}
