/**
 * Reference UI Primitives (generated - do not edit)
 * Run: node scripts/generate-primitives.cjs
 *
 * Box-based primitives with fixed element. Uses styled[tag] for correct ref types.
 * Public API omits 'as' so consumers get type-safe, non-polymorphic components.
 * Full Box flexibility: r, container, all style props.
 */

import { createBoxPrimitive } from './create-box-primitive.js'

export { TAGS as HTML_TAGS, type Tag as HtmlTag } from './tags.js'
export type { PrimitiveElement, PrimitiveProps } from './types.js'

export const A = createBoxPrimitive('a')
export const Abbr = createBoxPrimitive('abbr')
export const Address = createBoxPrimitive('address')
export const Area = createBoxPrimitive('area')
export const Article = createBoxPrimitive('article')
export const Aside = createBoxPrimitive('aside')
export const Audio = createBoxPrimitive('audio')
export const B = createBoxPrimitive('b')
export const Base = createBoxPrimitive('base')
export const Bdi = createBoxPrimitive('bdi')
export const Bdo = createBoxPrimitive('bdo')
export const Blockquote = createBoxPrimitive('blockquote')
export const Body = createBoxPrimitive('body')
export const Br = createBoxPrimitive('br')
export const Button = createBoxPrimitive('button')
export const Canvas = createBoxPrimitive('canvas')
export const Caption = createBoxPrimitive('caption')
export const Cite = createBoxPrimitive('cite')
export const Code = createBoxPrimitive('code')
export const Col = createBoxPrimitive('col')
export const Colgroup = createBoxPrimitive('colgroup')
export const Data = createBoxPrimitive('data')
export const Datalist = createBoxPrimitive('datalist')
export const Dd = createBoxPrimitive('dd')
export const Del = createBoxPrimitive('del')
export const Details = createBoxPrimitive('details')
export const Dfn = createBoxPrimitive('dfn')
export const Dialog = createBoxPrimitive('dialog')
export const Div = createBoxPrimitive('div')
export const Dl = createBoxPrimitive('dl')
export const Dt = createBoxPrimitive('dt')
export const Em = createBoxPrimitive('em')
export const Embed = createBoxPrimitive('embed')
export const Fieldset = createBoxPrimitive('fieldset')
export const Figcaption = createBoxPrimitive('figcaption')
export const Figure = createBoxPrimitive('figure')
export const Footer = createBoxPrimitive('footer')
export const Form = createBoxPrimitive('form')
export const H1 = createBoxPrimitive('h1')
export const H2 = createBoxPrimitive('h2')
export const H3 = createBoxPrimitive('h3')
export const H4 = createBoxPrimitive('h4')
export const H5 = createBoxPrimitive('h5')
export const H6 = createBoxPrimitive('h6')
export const Head = createBoxPrimitive('head')
export const Header = createBoxPrimitive('header')
export const Hgroup = createBoxPrimitive('hgroup')
export const Hr = createBoxPrimitive('hr')
export const Html = createBoxPrimitive('html')
export const I = createBoxPrimitive('i')
export const Iframe = createBoxPrimitive('iframe')
export const Img = createBoxPrimitive('img')
export const Input = createBoxPrimitive('input')
export const Ins = createBoxPrimitive('ins')
export const Kbd = createBoxPrimitive('kbd')
export const Label = createBoxPrimitive('label')
export const Legend = createBoxPrimitive('legend')
export const Li = createBoxPrimitive('li')
export const Link = createBoxPrimitive('link')
export const Main = createBoxPrimitive('main')
export const Map = createBoxPrimitive('map')
export const Mark = createBoxPrimitive('mark')
export const Menu = createBoxPrimitive('menu')
export const Menuitem = createBoxPrimitive('menuitem')
export const Meta = createBoxPrimitive('meta')
export const Meter = createBoxPrimitive('meter')
export const Nav = createBoxPrimitive('nav')
export const Noscript = createBoxPrimitive('noscript')
export const Obj = createBoxPrimitive('object')
export const Ol = createBoxPrimitive('ol')
export const Optgroup = createBoxPrimitive('optgroup')
export const Option = createBoxPrimitive('option')
export const Output = createBoxPrimitive('output')
export const P = createBoxPrimitive('p')
export const Param = createBoxPrimitive('param')
export const Picture = createBoxPrimitive('picture')
export const Pre = createBoxPrimitive('pre')
export const Progress = createBoxPrimitive('progress')
export const Q = createBoxPrimitive('q')
export const Rp = createBoxPrimitive('rp')
export const Rt = createBoxPrimitive('rt')
export const Ruby = createBoxPrimitive('ruby')
export const S = createBoxPrimitive('s')
export const Samp = createBoxPrimitive('samp')
export const Script = createBoxPrimitive('script')
export const Search = createBoxPrimitive('search')
export const Section = createBoxPrimitive('section')
export const Select = createBoxPrimitive('select')
export const Slot = createBoxPrimitive('slot')
export const Small = createBoxPrimitive('small')
export const Source = createBoxPrimitive('source')
export const Span = createBoxPrimitive('span')
export const Strong = createBoxPrimitive('strong')
export const Style = createBoxPrimitive('style')
export const Sub = createBoxPrimitive('sub')
export const Summary = createBoxPrimitive('summary')
export const Sup = createBoxPrimitive('sup')
export const Svg = createBoxPrimitive('svg')
export const Table = createBoxPrimitive('table')
export const Tbody = createBoxPrimitive('tbody')
export const Td = createBoxPrimitive('td')
export const Template = createBoxPrimitive('template')
export const Textarea = createBoxPrimitive('textarea')
export const Tfoot = createBoxPrimitive('tfoot')
export const Th = createBoxPrimitive('th')
export const Thead = createBoxPrimitive('thead')
export const Time = createBoxPrimitive('time')
export const Title = createBoxPrimitive('title')
export const Tr = createBoxPrimitive('tr')
export const Track = createBoxPrimitive('track')
export const U = createBoxPrimitive('u')
export const Ul = createBoxPrimitive('ul')
export const Var = createBoxPrimitive('var')
export const Video = createBoxPrimitive('video')
export const Wbr = createBoxPrimitive('wbr')