/**
 * Reference UI Primitives (generated - do not edit)
 * Run: node scripts/generate-primitives.cjs
 *
 * Box-based primitives with fixed element. Div = Box as="div", Span = Box as="span".
 * Public API omits 'as' so consumers get type-safe, non-polymorphic components.
 * Full Box flexibility: r, container, all style props.
 */

import * as React from 'react'
import { forwardRef } from 'react'
import { Box } from '../system/jsx/box.js'
import type { PrimitiveElement, PrimitiveProps } from './types.js'

export { TAGS as HTML_TAGS, type Tag as HtmlTag } from './tags.js'
export type { PrimitiveElement, PrimitiveProps } from './types.js'

export const A = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="a" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'a'> & React.RefAttributes<PrimitiveElement<'a'>>>
export const Abbr = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="abbr" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'abbr'> & React.RefAttributes<PrimitiveElement<'abbr'>>>
export const Address = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="address" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'address'> & React.RefAttributes<PrimitiveElement<'address'>>>
export const Area = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="area" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'area'> & React.RefAttributes<PrimitiveElement<'area'>>>
export const Article = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="article" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'article'> & React.RefAttributes<PrimitiveElement<'article'>>>
export const Aside = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="aside" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'aside'> & React.RefAttributes<PrimitiveElement<'aside'>>>
export const Audio = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="audio" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'audio'> & React.RefAttributes<PrimitiveElement<'audio'>>>
export const B = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="b" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'b'> & React.RefAttributes<PrimitiveElement<'b'>>>
export const Base = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="base" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'base'> & React.RefAttributes<PrimitiveElement<'base'>>>
export const Bdi = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="bdi" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'bdi'> & React.RefAttributes<PrimitiveElement<'bdi'>>>
export const Bdo = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="bdo" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'bdo'> & React.RefAttributes<PrimitiveElement<'bdo'>>>
export const Blockquote = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="blockquote" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'blockquote'> & React.RefAttributes<PrimitiveElement<'blockquote'>>>
export const Body = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="body" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'body'> & React.RefAttributes<PrimitiveElement<'body'>>>
export const Br = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="br" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'br'> & React.RefAttributes<PrimitiveElement<'br'>>>
export const Button = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="button" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'button'> & React.RefAttributes<PrimitiveElement<'button'>>>
export const Canvas = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="canvas" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'canvas'> & React.RefAttributes<PrimitiveElement<'canvas'>>>
export const Caption = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="caption" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'caption'> & React.RefAttributes<PrimitiveElement<'caption'>>>
export const Cite = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="cite" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'cite'> & React.RefAttributes<PrimitiveElement<'cite'>>>
export const Code = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="code" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'code'> & React.RefAttributes<PrimitiveElement<'code'>>>
export const Col = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="col" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'col'> & React.RefAttributes<PrimitiveElement<'col'>>>
export const Colgroup = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="colgroup" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'colgroup'> & React.RefAttributes<PrimitiveElement<'colgroup'>>>
export const Data = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="data" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'data'> & React.RefAttributes<PrimitiveElement<'data'>>>
export const Datalist = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="datalist" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'datalist'> & React.RefAttributes<PrimitiveElement<'datalist'>>>
export const Dd = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="dd" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'dd'> & React.RefAttributes<PrimitiveElement<'dd'>>>
export const Del = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="del" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'del'> & React.RefAttributes<PrimitiveElement<'del'>>>
export const Details = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="details" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'details'> & React.RefAttributes<PrimitiveElement<'details'>>>
export const Dfn = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="dfn" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'dfn'> & React.RefAttributes<PrimitiveElement<'dfn'>>>
export const Dialog = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="dialog" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'dialog'> & React.RefAttributes<PrimitiveElement<'dialog'>>>
export const Div = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="div" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'div'> & React.RefAttributes<PrimitiveElement<'div'>>>
export const Dl = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="dl" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'dl'> & React.RefAttributes<PrimitiveElement<'dl'>>>
export const Dt = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="dt" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'dt'> & React.RefAttributes<PrimitiveElement<'dt'>>>
export const Em = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="em" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'em'> & React.RefAttributes<PrimitiveElement<'em'>>>
export const Embed = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="embed" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'embed'> & React.RefAttributes<PrimitiveElement<'embed'>>>
export const Fieldset = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="fieldset" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'fieldset'> & React.RefAttributes<PrimitiveElement<'fieldset'>>>
export const Figcaption = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="figcaption" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'figcaption'> & React.RefAttributes<PrimitiveElement<'figcaption'>>>
export const Figure = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="figure" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'figure'> & React.RefAttributes<PrimitiveElement<'figure'>>>
export const Footer = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="footer" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'footer'> & React.RefAttributes<PrimitiveElement<'footer'>>>
export const Form = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="form" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'form'> & React.RefAttributes<PrimitiveElement<'form'>>>
export const H1 = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="h1" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'h1'> & React.RefAttributes<PrimitiveElement<'h1'>>>
export const H2 = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="h2" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'h2'> & React.RefAttributes<PrimitiveElement<'h2'>>>
export const H3 = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="h3" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'h3'> & React.RefAttributes<PrimitiveElement<'h3'>>>
export const H4 = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="h4" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'h4'> & React.RefAttributes<PrimitiveElement<'h4'>>>
export const H5 = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="h5" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'h5'> & React.RefAttributes<PrimitiveElement<'h5'>>>
export const H6 = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="h6" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'h6'> & React.RefAttributes<PrimitiveElement<'h6'>>>
export const Head = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="head" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'head'> & React.RefAttributes<PrimitiveElement<'head'>>>
export const Header = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="header" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'header'> & React.RefAttributes<PrimitiveElement<'header'>>>
export const Hgroup = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="hgroup" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'hgroup'> & React.RefAttributes<PrimitiveElement<'hgroup'>>>
export const Hr = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="hr" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'hr'> & React.RefAttributes<PrimitiveElement<'hr'>>>
export const Html = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="html" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'html'> & React.RefAttributes<PrimitiveElement<'html'>>>
export const I = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="i" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'i'> & React.RefAttributes<PrimitiveElement<'i'>>>
export const Iframe = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="iframe" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'iframe'> & React.RefAttributes<PrimitiveElement<'iframe'>>>
export const Img = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="img" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'img'> & React.RefAttributes<PrimitiveElement<'img'>>>
export const Input = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="input" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'input'> & React.RefAttributes<PrimitiveElement<'input'>>>
export const Ins = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="ins" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'ins'> & React.RefAttributes<PrimitiveElement<'ins'>>>
export const Kbd = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="kbd" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'kbd'> & React.RefAttributes<PrimitiveElement<'kbd'>>>
export const Label = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="label" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'label'> & React.RefAttributes<PrimitiveElement<'label'>>>
export const Legend = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="legend" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'legend'> & React.RefAttributes<PrimitiveElement<'legend'>>>
export const Li = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="li" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'li'> & React.RefAttributes<PrimitiveElement<'li'>>>
export const Link = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="link" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'link'> & React.RefAttributes<PrimitiveElement<'link'>>>
export const Main = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="main" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'main'> & React.RefAttributes<PrimitiveElement<'main'>>>
export const Map = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="map" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'map'> & React.RefAttributes<PrimitiveElement<'map'>>>
export const Mark = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="mark" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'mark'> & React.RefAttributes<PrimitiveElement<'mark'>>>
export const Menu = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="menu" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'menu'> & React.RefAttributes<PrimitiveElement<'menu'>>>
export const Menuitem = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="menuitem" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'menuitem'> & React.RefAttributes<PrimitiveElement<'menuitem'>>>
export const Meta = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="meta" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'meta'> & React.RefAttributes<PrimitiveElement<'meta'>>>
export const Meter = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="meter" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'meter'> & React.RefAttributes<PrimitiveElement<'meter'>>>
export const Nav = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="nav" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'nav'> & React.RefAttributes<PrimitiveElement<'nav'>>>
export const Noscript = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="noscript" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'noscript'> & React.RefAttributes<PrimitiveElement<'noscript'>>>
export const Obj = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="object" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'object'> & React.RefAttributes<PrimitiveElement<'object'>>>
export const Ol = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="ol" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'ol'> & React.RefAttributes<PrimitiveElement<'ol'>>>
export const Optgroup = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="optgroup" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'optgroup'> & React.RefAttributes<PrimitiveElement<'optgroup'>>>
export const Option = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="option" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'option'> & React.RefAttributes<PrimitiveElement<'option'>>>
export const Output = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="output" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'output'> & React.RefAttributes<PrimitiveElement<'output'>>>
export const P = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="p" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'p'> & React.RefAttributes<PrimitiveElement<'p'>>>
export const Param = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="param" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'param'> & React.RefAttributes<PrimitiveElement<'param'>>>
export const Picture = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="picture" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'picture'> & React.RefAttributes<PrimitiveElement<'picture'>>>
export const Pre = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="pre" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'pre'> & React.RefAttributes<PrimitiveElement<'pre'>>>
export const Progress = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="progress" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'progress'> & React.RefAttributes<PrimitiveElement<'progress'>>>
export const Q = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="q" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'q'> & React.RefAttributes<PrimitiveElement<'q'>>>
export const Rp = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="rp" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'rp'> & React.RefAttributes<PrimitiveElement<'rp'>>>
export const Rt = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="rt" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'rt'> & React.RefAttributes<PrimitiveElement<'rt'>>>
export const Ruby = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="ruby" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'ruby'> & React.RefAttributes<PrimitiveElement<'ruby'>>>
export const S = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="s" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'s'> & React.RefAttributes<PrimitiveElement<'s'>>>
export const Samp = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="samp" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'samp'> & React.RefAttributes<PrimitiveElement<'samp'>>>
export const Script = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="script" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'script'> & React.RefAttributes<PrimitiveElement<'script'>>>
export const Search = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="search" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'search'> & React.RefAttributes<PrimitiveElement<'search'>>>
export const Section = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="section" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'section'> & React.RefAttributes<PrimitiveElement<'section'>>>
export const Select = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="select" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'select'> & React.RefAttributes<PrimitiveElement<'select'>>>
export const Slot = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="slot" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'slot'> & React.RefAttributes<PrimitiveElement<'slot'>>>
export const Small = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="small" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'small'> & React.RefAttributes<PrimitiveElement<'small'>>>
export const Source = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="source" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'source'> & React.RefAttributes<PrimitiveElement<'source'>>>
export const Span = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="span" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'span'> & React.RefAttributes<PrimitiveElement<'span'>>>
export const Strong = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="strong" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'strong'> & React.RefAttributes<PrimitiveElement<'strong'>>>
export const Style = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="style" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'style'> & React.RefAttributes<PrimitiveElement<'style'>>>
export const Sub = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="sub" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'sub'> & React.RefAttributes<PrimitiveElement<'sub'>>>
export const Summary = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="summary" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'summary'> & React.RefAttributes<PrimitiveElement<'summary'>>>
export const Sup = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="sup" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'sup'> & React.RefAttributes<PrimitiveElement<'sup'>>>
export const Svg = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="svg" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'svg'> & React.RefAttributes<PrimitiveElement<'svg'>>>
export const Table = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="table" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'table'> & React.RefAttributes<PrimitiveElement<'table'>>>
export const Tbody = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="tbody" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'tbody'> & React.RefAttributes<PrimitiveElement<'tbody'>>>
export const Td = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="td" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'td'> & React.RefAttributes<PrimitiveElement<'td'>>>
export const Template = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="template" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'template'> & React.RefAttributes<PrimitiveElement<'template'>>>
export const Textarea = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="textarea" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'textarea'> & React.RefAttributes<PrimitiveElement<'textarea'>>>
export const Tfoot = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="tfoot" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'tfoot'> & React.RefAttributes<PrimitiveElement<'tfoot'>>>
export const Th = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="th" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'th'> & React.RefAttributes<PrimitiveElement<'th'>>>
export const Thead = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="thead" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'thead'> & React.RefAttributes<PrimitiveElement<'thead'>>>
export const Time = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="time" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'time'> & React.RefAttributes<PrimitiveElement<'time'>>>
export const Title = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="title" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'title'> & React.RefAttributes<PrimitiveElement<'title'>>>
export const Tr = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="tr" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'tr'> & React.RefAttributes<PrimitiveElement<'tr'>>>
export const Track = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="track" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'track'> & React.RefAttributes<PrimitiveElement<'track'>>>
export const U = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="u" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'u'> & React.RefAttributes<PrimitiveElement<'u'>>>
export const Ul = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="ul" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'ul'> & React.RefAttributes<PrimitiveElement<'ul'>>>
export const Var = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="var" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'var'> & React.RefAttributes<PrimitiveElement<'var'>>>
export const Video = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="video" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'video'> & React.RefAttributes<PrimitiveElement<'video'>>>
export const Wbr = forwardRef((props, ref) => { const { as: _, ...rest } = props as React.ComponentProps<typeof Box>; return <Box as="wbr" ref={ref as React.Ref<HTMLDivElement>} {...rest} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'wbr'> & React.RefAttributes<PrimitiveElement<'wbr'>>>